/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author Ahmad Fauzi
 */
public class AppPenampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form AppPenampilGambar
     */
    public AppPenampilGambar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutPanel = new javax.swing.JPanel();
        ironBtn = new javax.swing.JButton();
        spiderBtn = new javax.swing.JButton();
        hulkBtn = new javax.swing.JButton();
        keluarBtn = new javax.swing.JButton();
        gambarPanel = new javax.swing.JPanel();
        ironmanLabel = new javax.swing.JLabel();
        spidermanLabel = new javax.swing.JLabel();
        hulkLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penampil Gambar");
        setName("Tes"); // NOI18N

        layoutPanel.setBackground(new java.awt.Color(255, 255, 255));

        ironBtn.setBackground(new java.awt.Color(255, 255, 0));
        ironBtn.setText("Iron Man");
        ironBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ironBtnActionPerformed(evt);
            }
        });
        layoutPanel.add(ironBtn);

        spiderBtn.setBackground(new java.awt.Color(0, 0, 204));
        spiderBtn.setText("Spiderman");
        spiderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spiderBtnActionPerformed(evt);
            }
        });
        layoutPanel.add(spiderBtn);

        hulkBtn.setBackground(new java.awt.Color(0, 204, 0));
        hulkBtn.setText("Hulk");
        hulkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hulkBtnActionPerformed(evt);
            }
        });
        layoutPanel.add(hulkBtn);

        keluarBtn.setBackground(new java.awt.Color(255, 0, 0));
        keluarBtn.setText("Keluar");
        keluarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBtnActionPerformed(evt);
            }
        });
        layoutPanel.add(keluarBtn);

        getContentPane().add(layoutPanel, java.awt.BorderLayout.PAGE_START);

        gambarPanel.setLayout(new java.awt.CardLayout());

        ironmanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Ironman.jpg"))); // NOI18N
        gambarPanel.add(ironmanLabel, "0");

        spidermanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Spiderman.jpg"))); // NOI18N
        spidermanLabel.setMaximumSize(new java.awt.Dimension(400, 300));
        spidermanLabel.setPreferredSize(new java.awt.Dimension(400, 300));
        gambarPanel.add(spidermanLabel, "1");

        hulkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Hulk.jpg"))); // NOI18N
        gambarPanel.add(hulkLabel, "2");

        getContentPane().add(gambarPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spiderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spiderBtnActionPerformed
        // TODO add your handling code here:
        CardLayout Ft = (CardLayout)(gambarPanel.getLayout());
        Ft.show(gambarPanel,"1");
    }//GEN-LAST:event_spiderBtnActionPerformed

    private void ironBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ironBtnActionPerformed
        // TODO add your handling code here:
        CardLayout Ft = (CardLayout)(gambarPanel.getLayout());
        Ft.show(gambarPanel,"0");
    }//GEN-LAST:event_ironBtnActionPerformed

    private void hulkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hulkBtnActionPerformed
        // TODO add your handling code here:
        CardLayout Ft = (CardLayout)(gambarPanel.getLayout());
        Ft.show(gambarPanel,"2");
    }//GEN-LAST:event_hulkBtnActionPerformed

    private void keluarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBtnActionPerformed
        // TODO add your handling code here:
       int jawab = JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Keluar ?");
       if(jawab == JOptionPane.YES_OPTION){
          System.exit(0);
       }
    }//GEN-LAST:event_keluarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppPenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AppPenampilGambar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gambarPanel;
    private javax.swing.JButton hulkBtn;
    private javax.swing.JLabel hulkLabel;
    private javax.swing.JButton ironBtn;
    private javax.swing.JLabel ironmanLabel;
    private javax.swing.JButton keluarBtn;
    private javax.swing.JPanel layoutPanel;
    private javax.swing.JButton spiderBtn;
    private javax.swing.JLabel spidermanLabel;
    // End of variables declaration//GEN-END:variables
}
